#! /bin/sh

sxhkd &

bspc monitor -d Firefox Emacs Steam Movies V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar top &
polybar bottom &
setxkbmap -option ctrl:nocaps &
feh --bg-fill /home/lordjesus/Downloads/pixel-skull-20080.jpg &
compton -f
