#! /bin/sh

sxhkd &

bspc monitor -d Firefox Emacs Steam Movies V VI VII VIII IX X


getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
xrdb ~/.Xresources
xrdb -merge $(shuf -n1 -e ~/.colors/*)
paintee
# Only use the function above if the cache of paintee couldn't be found
if [ -e ~/.cache/paintee ]; then
	. ~/.cache/paintee
	else
	getcolors
fi


bspc config border_width         4
bspc config window_gap           8

bspc config focused_border_color "$BLUE"
bspc config normal_border_color  "$BLACK"
bspc config active_border_color  "$MAGENTA"
bspc config presel_feedback_color"$GREEN"
# bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config paddingless_monocle  true


hsetroot -solid '#8f6772' &
polybar top &
xsetroot -cursor_name left_ptr &
xrdb -load ~/.Xresources &
setxkbmap -option ctrl:nocaps &
xmodmap -e "keycode 107 = Super_R" &
feh --bg-fill /home/lordjesus/Downloads/pixel-skull-20080.jpg &
compton --vsync opengl -f &
dropbox start
