#! /bin/sh

sxhkd &

bspc monitor eDP-1 -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor LVDS1 -d II IV VI VIII
#bspc monitor VGA1 -d I III V VII IX X

getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
xrdb ~/.Xresources

bspc config border_width         4
bspc config window_gap           8

bspc config focused_border_color "$BLUE"
bspc config normal_border_color  "$BLACK"
bspc config active_border_color  "$MAGENTA"
bspc config presel_feedback_color"$GREEN"
# bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config paddingless_monocle  true


polybar left &
xsetroot -cursor_name left_ptr &
xrdb -load ~/.Xresources &
setxkbmap -option ctrl:nocaps &
xmodmap -e "keycode 107 = Super_R" &
feh --bg-fill /home/god/Pictures/kobayashi.jpg &
picom &
dunst
